# Generated by Django 2.2.20 on 2021-06-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_crop_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='pic',
            field=models.ManyToManyField(related_name='crops', to='farm.Image'),
        ),
    ]
