# Generated by Django 2.2.20 on 2021-06-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_auto_20210628_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='pic',
            new_name='image',
        ),
    ]
