# Generated by Django 2.2.20 on 2021-06-28 14:54

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_auto_20210628_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='imageF',
        ),
        migrations.AddField(
            model_name='crop',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
