# Generated by Django 2.2.20 on 2021-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_crop_image_ppoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
