# Generated by Django 2.2.20 on 2021-06-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_schedule_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('farmer_crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm.FarmerCrop')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm.Schedule')),
            ],
        ),
    ]
