# Generated by Django 2.2.20 on 2021-08-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_cropschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
