# Generated by Django 2.2.20 on 2021-08-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_quickguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickguide',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Crop'),
        ),
    ]
