# Generated by Django 2.2.20 on 2021-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_quickguide_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chemical',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
