# Generated by Django 2.2.20 on 2021-08-25 19:56

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_auto_20210825_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='chemicals/', verbose_name='Image'),
        ),
    ]
