# Generated by Django 2.2.20 on 2021-08-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_chemical_image_ppoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
