# Generated by Django 2.2.20 on 2021-08-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_auto_20210827_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='image_ppoi',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='image_ppoi',
        ),
        migrations.AlterField(
            model_name='chemical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
