# Generated by Django 2.2.20 on 2021-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_auto_20210828_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
