# Generated by Django 2.2.20 on 2021-09-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_crop_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickguide',
            name='icon_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
