# Generated by Django 2.2.20 on 2021-09-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_quickguide_icon_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropschedule',
            name='farmer_crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.FarmerCrop'),
        ),
        migrations.AlterField(
            model_name='cropschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Schedule'),
        ),
    ]
