# Generated by Django 2.2.20 on 2021-12-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_cropschedule_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
